[book]
authors = ["Oscar Aspelin"]
language = "en"
src = "src"
title = "Bioinformatics with Rust"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/OscarAspelin95/bioinformatics_with_rust"
mathjax-support = true
default-theme = "coal"
additional-css = ["src/assets/custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.playground]
editable = true

[output.html.print]
enable = true

[output.pdf]
optional = true

[preprocessor.mermaid]
command = "mdbook-mermaid"
